language: go

services:
  - docker

go:
  - 1.12.x

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq libtesseract-dev libleptonica-dev
  - TESSDATA_PREFIX=/usr/share/tesseract-ocr
  - sudo apt-get install -y -qq tesseract-ocr-eng
  - GO111MODULE=on go mod vendor
install:
  - go build

before_deploy:
  - docker build -t mhewedy/freeiptv .
#
deploy: # deploy to docker hub
  provider: script
  script:
    -bash docker_push
  on:
    tags: true
